# Generated by Django 3.2.9 on 2021-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.TextField(verbose_name='Краткое содержание'),
        ),
    ]
