# Generated by Django 3.2.9 on 2021-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelty', '0002_auto_20211219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='text',
            field=models.TextField(default='Текст отсутствует!', null=True, verbose_name='Текст'),
        ),
    ]
